name: Cypress Tests
on: [push]
jobs:

  Build-docker:
      runs-on: ubuntu-latest
      steps:
    - name: "Checkout repo"
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} #!!
        password: ${{ secrets.DOCKERHUB_TOKEN }} #!!
    - name: Create Network
      run: |
        docker network create -d bridge --subnet=192.168.0.0/16 my-bridge-network 


  Build-api:
    runs-on: ubuntu-latest
    needs: Build-docker
    run: |
      docker run -d --network=my-bridge-network -p 8082:80 -e DATABASE_CONECTION="Server=192.168.2.2,1433;Database=master;User Id=sa;Password=Test1234;" --name api neskred/dalle:api:back-end-api

  Build-front:
    runs-on: ubuntu-latest
    needs: Build-docker
    run: |
      docker run -d --network=my-bridge-network -p 80:80 --name front neskred/dalle:front-end

  Build-ware:
    runs-on: ubuntu-latest
    needs: Build-docker
    run: |
      docker run -d --network=my-bridge-network -p 8081:80 --name ware neskred/dalle:warehouse

  Build-db:
    runs-on: ubuntu-latest
    needs: Build-docker
    run: |
      docker run -d --network=my-bridge-network --ip 192.168.2.2 -p 1433:1433 --name database neskred/dalle:database_empty

  Build-images:
    runs-on: ubuntu-latest
    needs: Build-docker
    run: |
      docker run -d --network=my-bridge-network -p 8080:80 --name file neskred/dalle:imagesdb
  Cypress-Test:
    needs: [Build-images,Build-db,Build-api,Build-ware,Build-front]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
            command: npx cypress run
            browser: chrome
      - uses: actions/upload-artifact@v1
        with:
            name: cypress-videos
            path: cypress/videos