name: Cypress Tests
on: [push]
jobs:

  e2e-Testing:
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout repo"
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }} #!!
            password: ${{ secrets.DOCKERHUB_TOKEN }} #!!
        - name: Create Network
          run: |
            ls
            docker network create -d bridge --subnet=192.168.0.0/16 my-bridge-network 

        - name: Run container front
          run: |
            ls
            docker run -d --network=my-bridge-network -p 80:80 --name front neskred/dalle:front-end

        - name: Run container warehouse
          run: |
            ls
            docker run -d --network=my-bridge-network -p 8081:80 --name ware neskred/dalle:warehouse

        - name: Run container database
          run: |
            ls
            docker run -d --network=my-bridge-network --ip 192.168.2.2 -p 1433:1433 --name database neskred/dalle:database_empty

        - name: Run container image-db
          run: |
            ls
            docker run -d --network=my-bridge-network -p 8080:80 --name file neskred/dalle:imagesdb

        - name: Run container api
          run: |
            ls
            docker run -d --network=my-bridge-network -p 8082:80 -e DATABASE_CONECTION='Server=192.168.2.2,1433;Database=master;User Id=sa;Password=Test1234;' --name api neskred/dalle:back-end-api
            docker network inspect my-bridge-network
        
        - name: check api running
          shell: pwsh
          run: |
            $Response = Invoke-WebRequest -URI http://localhost:8082/api/Paintings



        - name: Run Cypress Test
          uses: cypress-io/github-action@v4
          with:
              command: npx cypress run
              browser: chrome
        - uses: actions/upload-artifact@v1
          if: always()
          with:
              name: cypress-videos
              path: cypress/videos